events: add Art of Scala 2023
scala/scala-lang pull request #1567
Opened 2023-10-25 16:45 UTC by SethTisue

2023-10-25 16:46 UTC, SethTisue commented
rendered locally

<img width="1180" alt="Screenshot 2023-10-25 at 9 45 53 AM" src="https://github.com/scala/scala-lang/assets/161079/440d42ea-e320-4bc8-8bfb-285862979805">

2023-10-29 23:56 UTC, Philippus requested changes

2023-10-29 23:56 UTC, Philippus commented on _events/2023-11-17-art-of-scala.md
> +title: The Art of Scala
The site doesn't say "The"
```suggestion
title: Art of Scala
```

2023-10-29 23:56 UTC, Philippus commented on _events/2023-11-17-art-of-scala.md
> +end: 13 November 2023
```suggestion
start: 17 November 2023
end: 17 November 2023
```

2023-10-30 00:14 UTC, SethTisue commented
gah, thanks @Philippus

2023-10-30 00:15 UTC, merged

2023-10-30 00:16 UTC, SethTisue commented
https://www.scala-lang.org/events/